#!/usr/bin/python3


import sys
import datetime

def country(c):

    if c == 'america':
        t = -14
    elif c == 'china':
        t= -1
    elif c == 'england':
        t = -9
    elif c == 'russia':
        t = -4
    else :
        t = 24

    return t

time_now = datetime.datetime.now()

count = sys.argv[1]
t = country(count)
if t != 24:
    time_offset = datetime.timedelta(hours=t)
    time_offset_now = time_now + time_offset
    print(time_offset_now.strftime("%H:%M:%S"))
else :
    print('Not Implement')

