name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
    matrix:
      gcc-version: 7.5.0
    steps:
    - uses: actions/checkout@v3
    - name: All test
      run: bash -xv ./lang.c

